baseURL = "https://evtdanya.github.io/"
languageCode = "en-us"
title = "Danil | AppSec & Security research"
theme = "PaperMod"

[author]
  name = "Danil"

[params]
  homeInfoParams = {Title = "Hi, I'm Danil", Content = "AppSec engineer | Bug hunter | Security researcher"}
  ShowReadingTime = true
  ShowShareButtons = false